"""empty message

Revision ID: 2002c043c296
Revises: 0c3b7a7267d9
Create Date: 2021-02-19 18:23:18.705300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2002c043c296'
down_revision = '0c3b7a7267d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'description',
               existing_type=sa.String(length=255),
               type_=sa.String(length=2200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'description',
               existing_type=sa.String(length=2200),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
